const COLLECTION_USERS = 'USERS';
const COLLECTION_CALL = 'CALL';
const COLLECTION_OTHER = 'OTHER';
const COLLECTION_PRIVATE_ENTERPRISE = 'PRIVATE_ENTERPRISE';
const COLLECTION_PROFESSORLAB = 'PROFESSOR&LAB';
const COLLECTION_PUBLIC_ENTERPRISE = 'PUBLIC_ENTERPRISE';
const COLLECTION_YONSEI = 'YONSEI';
const COLLECTION_YONSE_MSE = 'YONSEI_MSE';
const COLLECTION_YOUTUBE = 'YOUTUBE';

const KEY_USERKEY = 'user_key';
const KEY_EMAIL = 'email';
const KEY_STU_NUMBER = 'stu_num';
const KEY_CATEGORY = 'category';

const KEY_POSTKEY = 'post_key';
const KEY_NAME = 'name';
const KEY_PHONE_NUMBER = 'number';
const KEY_URL = 'url';
const KEY_LAB_URL = 'lab_url';
const KEY_PROFESSOR_URL = 'professor_url';